name: Build

on:
    workflow_dispatch:
    schedule:
        - cron: "0 0 * * *"

jobs:
    build-normal-base:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4

            - name: Set up QEMU
              uses: docker/setup-qemu-action@v3

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Build and push
              uses: docker/build-push-action@v5
              with:
                context: .
                push: true
                tags: jacoblincool/playwright:base
                target: base
                platforms: linux/amd64,linux/arm64/v8
                cache-from: type=gha
                cache-to: type=gha,mode=max

            - name: Build and push
              uses: docker/build-push-action@v5
              with:
                context: .
                push: true
                tags: jacoblincool/playwright:pnpm
                target: pnpm
                platforms: linux/amd64,linux/arm64/v8
                cache-from: type=gha
                cache-to: type=gha,mode=max

    build-normal:
        needs:
            - build-normal-base
        strategy:
            matrix:
                target:
                    - chromium
                    - firefox
                    - webkit
                    - chrome
                    - msedge
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4

            - name: Set up QEMU
              uses: docker/setup-qemu-action@v3

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Build and push
              uses: docker/build-push-action@v5
              with:
                context: .
                push: true
                tags: jacoblincool/playwright:${{ matrix.target }}
                target: ${{ matrix.target }}
                platforms: linux/amd64,linux/arm64/v8
                cache-from: type=gha
                cache-to: type=gha,mode=max
    

    build-normal-all:
        needs:
            - build-normal
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4

            - name: Set up QEMU
              uses: docker/setup-qemu-action@v3

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Build and push
              uses: docker/build-push-action@v5
              with:
                context: .
                push: true
                tags: jacoblincool/playwright:all
                target: all
                platforms: linux/amd64,linux/arm64/v8
                cache-from: type=gha
                cache-to: type=gha,mode=max

    build-light:
        name: Build Light Docker Images
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4

            - name: Set up QEMU
              uses: docker/setup-qemu-action@v3

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Build and push
              uses: docker/build-push-action@v5
              with:
                context: .
                push: true
                tags: jacoblincool/playwright:base-light
                target: base-light
                platforms: linux/amd64,linux/arm64/v8
                cache-from: type=gha
                cache-to: type=gha,mode=max

            - name: Build and push
              uses: docker/build-push-action@v5
              with:
                context: .
                push: true
                tags: jacoblincool/playwright:chromium-light
                target: chromium-light
                platforms: linux/amd64,linux/arm64/v8
                cache-from: type=gha
                cache-to: type=gha,mode=max

    build-server:
        needs:
            - build-normal
            - build-light
        strategy:
            matrix:
                target:
                    - chromium-server
                    - firefox-server
                    - webkit-server
                    - chrome-server
                    - msedge-server
                    - chromium-light-server
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4

            - name: Set up QEMU
              uses: docker/setup-qemu-action@v3

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Build and push
              uses: docker/build-push-action@v5
              with:
                context: .
                push: true
                tags: jacoblincool/playwright:${{ matrix.target }}
                target: ${{ matrix.target }}
                platforms: linux/amd64,linux/arm64/v8
                cache-from: type=gha
                cache-to: type=gha,mode=max

    update-readme:
        name: Update Docker Readme
        runs-on: ubuntu-latest
        needs:
            - build-normal-all
            - build-server
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4

            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Tag Image Alias
              run: ./scripts/tag.sh
              env:
                  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
                  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Update Readme
              run: node ./scripts/update.js

            - name: Docker Hub Description
              uses: peter-evans/dockerhub-description@v4
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}
                  repository: jacoblincool/playwright
