name: Test

on:
    workflow_dispatch:
    pull_request:
        branches:
            - main
    push:
        branches:
            - main
        paths-ignore:
            - "**/*.md"

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Setup PNPM
              uses: pnpm/action-setup@v2.2.4
              with:
                  version: latest
                  run_install: false

            - name: Install Test Dependencies
              run: cd test && pnpm install

            - name: Set up QEMU
              uses: docker/setup-qemu-action@v2

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2

            - name: Build Images
              run: ./scripts/local.sh

            - name: Check Versions
              run: |
                  docker run --rm jacoblincool/playwright:base
                  docker run --rm jacoblincool/playwright:chrome
                  docker run --rm jacoblincool/playwright:chromium
                  docker run --rm jacoblincool/playwright:firefox
                  docker run --rm jacoblincool/playwright:webkit
                  docker run --rm jacoblincool/playwright:all

            - name: Test
              run: ./test/test.sh
